# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf
source = ~/.config/hypr/plugin-split-monitor-workspace.conf
# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
exec-once = clipse -listen

# === CLIPSE - Gestor de portapapeles ===
exec-once = clipse -listen

windowrule {
  name = clipse-rules
  match:class = clipse
  float = on
  size = 650 550
  center = on
  stay_focused = on
}

# Atajo Super + V
bind = SUPER, V, exec, alacritty --class clipse -e clipse

# En ~/.config/hypr/hyprland.conf

cursor {
    # Evita que el foco salte a otro monitor/workspace automáticamente
    no_warps = true
}

binds {
    # Esto evita que al intentar mover el foco a la izquierda/derecha
    # en los bordes, te lleve al workspace vecino.
    workspace_back_and_forth = false
    allow_workspace_cycles = false
}

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
