# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    # border_size = 0

    # Master layout: master a la izquierda, nuevas ventanas a la derecha
   layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#
decoration {
    # Use round window corners
    rounding = 5
    rounding_power = 4.0

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}


# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# Master layout: nuevas ventanas como esclavas a la derecha del todo
master {
    orientation = right
    new_status = slave
    new_on_active = false
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

scrolling {
    # Scroll through windows in the current workspace
    # scroll_through_windows = true
    column_width = 0.75
}